-- CreateEnum
CREATE TYPE "Entity" AS ENUM ('THE BURIED', 'THE CORRUPTION', 'THE DARK', 'THE DESOLATION', 'THE END', 'THE EXTINCTION', 'THE EYE', 'THE FLESH', 'THE HUNT', 'THE LONELY', 'THE SLAUGHTER', 'THE SPIRAL', 'THE STRANGER', 'THE VAST', 'THE WEB');

-- AlterTable
ALTER TABLE "Episode" ADD COLUMN     "entity" "Entity" NOT NULL DEFAULT 'THE EYE';
